
#ifndef _ENCLAVE_MIXIN
#define _ENCLAVE_MIXIN

#define SHIM_NSYSCALLS 330

#if defined(__x86_64__)
# define SHIM_TCB_OFFSET    80
#else
# define SHIM_TCB_OFFSET    44
#endif


#ifdef __ASSEMBLER__

#else /* !__ASSEMBLER__ */
#include <sgx.h>

extern unsigned long current_brk;
extern unsigned long real_brk;
extern int no_rdrand;
extern int thread_priority;
void *get_syscall_buffer(unsigned long);
void free_syscall_buffer(void *);
char *string_buffer_out(const char* str);
void free_string_buffer(char *);
char **string_array_buffer_out(const char *const arr[]);
void free_string_array_buffer(char **);
SGX_tcs *alloc_new_thread(unsigned long sp, unsigned long tls);

typedef void(*shim_fp)(void);
long syscall_pass(long, long, long, long, long, long);
long __syscall_pass(long, long, long, long, long, long);
long syscall_fail_soft(void);

long __shim_read(long, long , long);
long __shim_write(long, long, long);
long __shim_open(long, long , long);
long __shim_close(long);
long __shim_stat(long, long);
long __shim_fstat(long, long);
long __shim_lstat(long, long);
long __shim_poll(long, long, long);
long __shim_lseek(long, long, long);
long __shim_mmap(long, long, long, long, long, long);
long __shim_mprotect(long, long, long);
long __shim_munmap(long, long);
long __shim_brk(long);
long __shim_rt_sigaction(long, long, long, long);
long __shim_rt_sigprocmask(long, long, long, long);
long __shim_rt_sigreturn(long);
long __shim_ioctl(long, long, long);
long __shim_pread64(long, long, long, long);
long __shim_pwrite64(long, long, long, long);
long __shim_readv(long, long, long);
long __shim_writev(long, long, long);
long __shim_access(long, long);
long __shim_pipe(long);
long __shim_select(long, long, long, long, long);
long __shim_sched_yield(void);
long __shim_mremap(long, long, long, long, long);
long __shim_msync(long, long, long);
long __shim_mincore(long, long, long);
long __shim_madvise(long, long, long);
long __shim_shmget(long, long, long);
long __shim_shmat(long, long, long);
long __shim_shmctl(long, long, long);
long __shim_dup(long);
long __shim_dup2(long, long);
long __shim_pause(void);
long __shim_nanosleep(long, long);
long __shim_getitimer(long, long);
long __shim_alarm(long);
long __shim_setitimer(long, long, long);
long __shim_getpid(void);
long __shim_sendfile(long, long, long, long);
long __shim_socket(long, long, long);
long __shim_connect(long, long, long);
long __shim_accept(long, long, long);
long __shim_sendto(long, long, long, long, long, long);
long __shim_recvfrom(long, long, long, long, long, long);
long __shim_sendmsg(long, long, long);
long __shim_recvmsg(long, long, long);
long __shim_shutdown(long, long);
long __shim_bind(long, long, long);
long __shim_listen(long, long);
long __shim_getsockname(long, long, long);
long __shim_getpeername(long, long, long);
long __shim_socketpair(long, long, long, long);
long __shim_setsockopt(long, long, long, long, long);
long __shim_getsockopt(long, long, long, long, long);
long __shim_clone(long, long, long, long, long);
long __shim_fork(void);
long __shim_vfork(void);
long __shim_execve(long, long, long);
long __shim_exit(long);
long __shim_wait4(long, long, long, long);
long __shim_kill(long, long);
long __shim_uname(long);
long __shim_semget(long, long, long);
long __shim_semop(long, long, long);
long __shim_semctl(long, long, long, long);
long __shim_shmdt(long);
long __shim_msgget(long, long);
long __shim_msgsnd(long, long, long, long);
long __shim_msgrcv(long, long, long, long, long);
long __shim_msgctl(long, long, long);
long __shim_fcntl(long, long, long);
long __shim_flock(long, long);
long __shim_fsync(long);
long __shim_fdatasync(long);
long __shim_truncate(long, long);
long __shim_ftruncate(long, long);
long __shim_getdents(long, long, long);
long __shim_getcwd(long, long);
long __shim_chdir(long);
long __shim_fchdir(long);
long __shim_rename(long, long);
long __shim_mkdir(long, long);
long __shim_rmdir(long);
long __shim_creat(long, long);
long __shim_link(long, long);
long __shim_unlink(long);
long __shim_symlink(long, long);
long __shim_readlink(long, long, long);
long __shim_chmod(long, long);
long __shim_fchmod(long, long);
long __shim_chown(long, long, long);
long __shim_fchown(long, long, long);
long __shim_lchown(long, long, long);
long __shim_umask(long);
long __shim_gettimeofday(long, long);
long __shim_getrlimit(long, long);
long __shim_getrusage(long, long);
long __shim_sysinfo(long);
long __shim_times(long);
long __shim_ptrace(long, long, long, long);
long __shim_getuid(void);
long __shim_syslog(long, long, long);
long __shim_getgid(void);
long __shim_setuid(long);
long __shim_setgid(long);
long __shim_geteuid(void);
long __shim_getegid(void);
long __shim_setpgid(long, long);
long __shim_getppid(void);
long __shim_getpgrp(void);
long __shim_setsid(void);
long __shim_setreuid(long, long);
long __shim_setregid(long, long);
long __shim_getgroups(long, long);
long __shim_setgroups(long, long);
long __shim_setresuid(long, long, long);
long __shim_getresuid(long, long, long);
long __shim_setresgid(long, long, long);
long __shim_getresgid(long, long, long);
long __shim_getpgid(long);
long __shim_setfsuid(long);
long __shim_setfsgid(long);
long __shim_getsid(long);
long __shim_capget(long, long);
long __shim_capset(long, long);
long __shim_rt_sigpending(long, long);
long __shim_rt_sigtimedwait(long, long, long, long);
long __shim_rt_sigqueueinfo(long, long, long);
long __shim_rt_sigsuspend(long, long);
long __shim_sigaltstack(long, long);
long __shim_utime(long, long);
long __shim_mknod(long, long, long);
long __shim_uselib(long);
long __shim_personality(long);
long __shim_ustat(long, long);
long __shim_statfs(long, long);
long __shim_fstatfs(long, long);
long __shim_getpriority(long, long);
long __shim_setpriority(long, long, long);
long __shim_sched_setparam(long, long);
long __shim_sched_getparam(long, long);
long __shim_sched_setscheduler(long, long, long);
long __shim_sched_getscheduler(long);
long __shim_sched_get_priority_max(long);
long __shim_sched_get_priority_min(long);
long __shim_sched_rr_get_interval(long, long);
long __shim_mlock(long, long);
long __shim_munlock(long, long);
long __shim_mlockall(long);
long __shim_munlockall(void);
long __shim_vhangup(void);
long __shim_modify_ldt(long, long, long);
long __shim_pivot_root(long, long);
long __shim__sysctl(long);
long __shim_prctl(long, long, long, long, long);
long __shim_arch_prctl(long, long);
long __shim_adjtimex(long);
long __shim_setrlimit(long, long);
long __shim_chroot(long);
long __shim_sync(void);
long __shim_acct(long);
long __shim_settimeofday(long, long);
long __shim_mount(long, long, long, long, long);
long __shim_umount2(long, long);
long __shim_swapon(long, long);
long __shim_swapoff(long);
long __shim_reboot(long, long, long, long);
long __shim_sethostname(long, long);
long __shim_setdomainname(long, long);
long __shim_iopl(long);
long __shim_ioperm(long, long, long);
long __shim_create_module(long, long);
long __shim_init_module(long, long, long);
long __shim_delete_module(long, long);
long __shim_get_kernel_syms(long);
long __shim_query_module(long, long, long, long, long);
long __shim_quotactl(long, long, long, long);
long __shim_nfsservctl(long, long, long);
long __shim_gettid(void);
long __shim_readahead(long, long, long);
long __shim_setxattr(long, long, long, long, long);
long __shim_lsetxattr(long, long, long, long, long);
long __shim_fsetxattr(long, long, long, long, long);
long __shim_getxattr(long, long, long, long);
long __shim_lgetxattr(long, long, long, long);
long __shim_fgetxattr(long, long, long, long);
long __shim_listxattr(long, long, long);
long __shim_llistxattr(long, long, long);
long __shim_flistxattr(long, long, long);
long __shim_removexattr(long, long);
long __shim_lremovexattr(long, long);
long __shim_fremovexattr(long, long);
long __shim_tkill(long, long);
long __shim_time(long);
long __shim_futex(long, long, long, long, long, long);
long __shim_sched_setaffinity(long, long, long);
long __shim_sched_getaffinity(long, long, long);
long __shim_set_thread_area(long);
long __shim_io_setup(long, long);
long __shim_io_destroy(long);
long __shim_io_getevents(long, long, long, long, long);
long __shim_io_submit(long, long, long);
long __shim_io_cancel(long, long, long);
long __shim_get_thread_area(long);
long __shim_lookup_dcookie(long, long, long);
long __shim_epoll_create(long);
long __shim_remap_file_pages(long, long, long, long, long);
long __shim_getdents64(long, long, long);
long __shim_set_tid_address(long);
long __shim_restart_syscall(void);
long __shim_semtimedop(long, long, long, long);
long __shim_fadvise64(long, long, long, long);
long __shim_timer_create(long, long, long);
long __shim_timer_settime(long, long, long, long);
long __shim_timer_gettime(long, long);
long __shim_timer_getoverrun(long);
long __shim_timer_delete(long);
long __shim_clock_settime(long, long);
long __shim_clock_gettime(long, long);
long __shim_clock_getres(long, long);
long __shim_clock_nanosleep(long, long, long, long);
long __shim_exit_group(long);
long __shim_epoll_wait(long, long, long, long);
long __shim_epoll_ctl(long, long, long, long);
long __shim_tgkill(long, long, long);
long __shim_utimes(long, long);
long __shim_mbind(long, long, long, long, long, long);
long __shim_set_mempolicy(long, long, long);
long __shim_get_mempolicy(long, long, long, long, long);
long __shim_mq_open(long, long, long, long);
long __shim_mq_unlink(long);
long __shim_mq_timedsend(long, long, long, long, long);
long __shim_mq_timedreceive(long, long, long, long, long);
long __shim_mq_notify(long, long);
long __shim_mq_getsetattr(long, long, long);
long __shim_kexec_load(long, long, long, long);
long __shim_waitid(long, long, long, long, long);
long __shim_add_key(long, long, long, long, long);
long __shim_request_key(long, long, long, long);
long __shim_keyctl(long, long, long, long, long);
long __shim_ioprio_set(long, long, long);
long __shim_ioprio_get(long, long);
long __shim_inotify_init(void);
long __shim_inotify_add_watch(long, long, long);
long __shim_inotify_rm_watch(long, long);
long __shim_migrate_pages(long, long, long, long);
long __shim_openat(long, long, long, long);
long __shim_mkdirat(long, long, long);
long __shim_mknodat(long, long, long, long);
long __shim_fchownat(long, long, long, long, long);
long __shim_futimesat(long, long, long);
long __shim_newfstatat(long, long, long, long);
long __shim_unlinkat(long, long, long);
long __shim_renameat(long, long, long, long);
long __shim_linkat(long, long, long, long, long);
long __shim_symlinkat(long, long, long);
long __shim_readlinkat(long, long, long, long);
long __shim_fchmodat(long, long, long, long);
long __shim_faccessat(long, long, long, long);
long __shim_pselect6(long, long, long, long, long, long);
long __shim_ppoll(long, long, long, long, long);
long __shim_unshare(long);
long __shim_set_robust_list(long, long);
long __shim_get_robust_list(long, long, long);
long __shim_splice(long, long, long, long, long, long);
long __shim_tee(long, long, long, long);
long __shim_sync_file_range(long, long, long, long);
long __shim_vmsplice(long, long, long, long);
long __shim_move_pages(long, long, long, long, long, long);
long __shim_utimensat(long, long, long, long);
long __shim_epoll_pwait(long, long, long, long, long);
long __shim_signalfd(long, long, long);
long __shim_timerfd_create(long, long);
long __shim_eventfd(long, long);
long __shim_fallocate(long, long, long, long);
long __shim_timerfd_settime(long, long, long, long);
long __shim_timerfd_gettime(long, long);
long __shim_accept4(long, long, long, long);
long __shim_signalfd4(long, long, long, long);
long __shim_eventfd2(long, long);
long __shim_epoll_create1(long);
long __shim_dup3(long, long, long);
long __shim_pipe2(long, long);
long __shim_inotify_init1(long);
long __shim_preadv(long, long, long, long, long);
long __shim_pwritev(long, long, long, long, long);
long __shim_rt_tgsigqueueinfo(long, long, long, long);
long __shim_perf_event_open(long, long, long, long, long);
long __shim_recvmmsg(long, long, long, long, long);
long __shim_fanotify_init(long, long);
long __shim_fanotify_mark(long, long, long, long, long);
long __shim_syncfs(long);
long __shim_sendmmsg(long, long, long, long);
long __shim_setns(long, long);
long __shim_getcpu(long, long, long);
long __shim_process_vm_readv(long, long, long, long, long, long);
long __shim_process_vm_writev(long, long, long, long, long, long);
long __shim_kcmp(long, long, long, long, long);
long __shim_finit_module(long, long, long);
long __shim_sched_setattr(long, long, long);
long __shim_sched_getattr(long, long, long);
long __shim_renameat2(long, long, long, long, long);
long __shim_enclaveinit(void);
long __shim_enclave_aug(long, long, long, long);
long __shim_enclave_release(long, long);
long __shim_enclave_drop(long, long);
long __shim_getrandom(long, long, long);
long __shim_lockmprotect(long, long);
#endif

#endif /* _ENCLAVE_MIXIN */
